# Generated by Django 2.1.3 on 2018-11-28 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='diseases',
            fields=[
                ('diseases_id', models.IntegerField(primary_key=True, serialize=False)),
                ('diseases_name', models.CharField(max_length=50)),
                ('diseases_type', models.CharField(max_length=50)),
                ('diseases_syptom', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='genric_medicines',
            fields=[
                ('medicine_id', models.IntegerField(primary_key=True, serialize=False)),
                ('medicine_name', models.CharField(max_length=50)),
                ('medicine_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='nongenric_medicines',
            fields=[
                ('medicine_id', models.IntegerField(primary_key=True, serialize=False)),
                ('medicine_name', models.CharField(max_length=50)),
                ('medicine_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='patients',
            fields=[
                ('patient_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('contact', models.IntegerField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('disease_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='patients_register',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('User_id', models.IntegerField()),
                ('Contact', models.IntegerField()),
                ('Age', models.IntegerField()),
                ('Date_of_birth', models.DateField()),
                ('Gender', models.CharField(max_length=50)),
                ('Occupation', models.CharField(max_length=100)),
                ('Height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Email', models.EmailField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Addres', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('Prescription_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Genric_medicine', models.CharField(max_length=120)),
                ('Nongenric_medicines', models.CharField(max_length=20)),
                ('Test', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Results', models.CharField(max_length=500)),
                ('patients_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.patients')),
            ],
        ),
    ]
